version: '3'

services:
  app:
    build:
      context: .  # Assuming your Dockerfile is in the same directory as this docker-compose.yml
      dockerfile: Dockerfile  # Optional if the Dockerfile is named "Dockerfile"
    ports:
      - "5000:5000"  # Maps local port 5000 to container port 5000
    environment:
      - FLASK_ENV=development  # Optional: Sets the Flask environment to development
    command: gunicorn -b 0.0.0.0:5000 app:app  # Starts the app using Gunicorn

    # Optional:
    # volumes:
    #   - .:/app  # If you want to mount the current directory into the container (useful for development)
